### ISSUE TITLE
error with babel 7 and material-ui@next

### ISSUE THREAD

**Issue by BjornMelgaard** [umidbekkarimov/babel-plugin-direct-import#10]
```
 ~/work/nuuz-chrome-extension   react ●✚  yr dev
yarn run v1.3.2
$ node scripts/dev
/home/bjorn/work/nuuz-chrome-extension/node_modules/@babel/core/lib/config/build-config-chain.js:37
    if (e.code !== "BABEL_IGNORED_FILE") throw e;
                                         ^

Error: .plugins[3][1] must be an object, false, or undefined
    at assertPluginItem (/home/bjorn/work/nuuz-chrome-extension/node_modules/@babel/core/lib/config/option-assertions.js:127:15)
    at /home/bjorn/work/nuuz-chrome-extension/node_modules/@babel/core/lib/config/option-assertions.js:104:14
    at Array.forEach (<anonymous>)
    at assertPluginList (/home/bjorn/work/nuuz-chrome-extension/node_modules/@babel/core/lib/config/option-assertions.js:103:9)
    at /home/bjorn/work/nuuz-chrome-extension/node_modules/@babel/core/lib/config/options.js:71:20
    at Array.forEach (<anonymous>)
    at validate (/home/bjorn/work/nuuz-chrome-extension/node_modules/@babel/core/lib/config/options.js:57:21)
    at /home/bjorn/work/nuuz-chrome-extension/node_modules/@babel/core/lib/config/build-config-chain.js:172:36
    at cachedFunction (/home/bjorn/work/nuuz-chrome-extension/node_modules/@babel/core/lib/config/caching.js:40:17)
    at ConfigChainBuilder.mergeConfigFile (/home/bjorn/work/nuuz-chrome-extension/node_modules/@babel/core/lib/config/build-config-chain.js:69:17)
Done in 1.38s.

```

[babelrc](https://github.com/BjornMelgaard/react-chrome-extension-boilerplate/blob/react/.babelrc#L18) [deps](https://github.com/BjornMelgaard/react-chrome-extension-boilerplate/blob/react/package.json#L52)

**Comment by umidbekkarimov** [comment]
Hello @BjornMelgaard ! Please check [next](https://github.com/umidbekkarimov/babel-plugin-direct-import/tree/next) branch.

See also [note for babel@7 users](https://github.com/umidbekkarimov/babel-plugin-direct-import#babel-7-user).

**Comment by BjornMelgaard** [comment]
@umidbekkarimov I was trying this on next branch

see deps
https://github.com/BjornMelgaard/react-chrome-extension-boilerplate/blob/react/package.json#L52

**Comment by umidbekkarimov** [comment]
Please check [installation](https://github.com/umidbekkarimov/babel-plugin-direct-import/tree/next#installation) and [usage](https://github.com/umidbekkarimov/babel-plugin-direct-import/tree/next#via-babelrc-recommended) examples. You have problem with wrong options.

**Comment by BjornMelgaard** [comment]
@umidbekkarimov ups, see it, I used options from master branch, sorry
